# Generated by Django 4.2.19 on 2025-03-01 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='ชื่อคำสั่ง')),
                ('number', models.IntegerField(verbose_name='เลขที่คำสั่ง')),
                ('year', models.IntegerField(default=2568, validators=[django.core.validators.MinValueValidator(2550, message='ปีต้องไม่ต่ำกว่า 2550'), django.core.validators.MaxValueValidator(2580, message='ปีต้องไม่เกิน 2580')], verbose_name='ปี')),
                ('file', models.FileField(blank=True, null=True, upload_to='command_files/', verbose_name='ไฟล์')),
            ],
            options={
                'verbose_name': '2. คำสั่ง',
                'verbose_name_plural': '2. คำสั่ง',
                'ordering': ['year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='NationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(default=2568, verbose_name='ปีงบประมาณ')),
                ('number', models.IntegerField(default=1, verbose_name='ครั้งที่')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อการประชุม')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='วันที่')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='meeting_pictures/', verbose_name='รูปภาพ')),
                ('file', models.FileField(blank=True, null=True, upload_to='meeting_files/', verbose_name='ไฟล์')),
            ],
            options={
                'verbose_name': '1. การประชุม.',
                'verbose_name_plural': '1. การประชุม.',
                'ordering': ['meeting_date'],
            },
        ),
    ]
