# Generated by Django 4.2.19 on 2025-03-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='ลงวันที่'),
        ),
    ]
