# Generated by Django 4.2.19 on 2025-03-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0002_command_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['fiscal_year', 'number'], 'verbose_name': '2. คำสั่ง', 'verbose_name_plural': '2. คำสั่ง'},
        ),
        migrations.RenameField(
            model_name='command',
            old_name='year',
            new_name='fiscal_year',
        ),
    ]
