# Generated by Django 4.2.19 on 2025-03-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0003_alter_command_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['-date'], 'verbose_name': '2. คำสั่ง', 'verbose_name_plural': '2. คำสั่ง'},
        ),
        migrations.AlterModelOptions(
            name='nationmeeting',
            options={'ordering': ['-meeting_date'], 'verbose_name': '1. การประชุม.', 'verbose_name_plural': '1. การประชุม.'},
        ),
    ]
