# Generated by Django 4.2.19 on 2025-02-12 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('responsible', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('province', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(default=2568)),
                ('number', models.IntegerField(default=1)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('report_send', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='meeting_pictures/')),
                ('file', models.FileField(blank=True, null=True, upload_to='meeting_files/')),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('P', 'แผน'), ('D', 'ดำเนินการแล้ว'), ('A', 'ตรวจสอบแล้ว')], default='P', max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(default=2568)),
                ('meeting_number', models.IntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_objectives', to='core.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.section'),
        ),
    ]
