# Generated by Django 4.2.19 on 2025-02-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['section__number'], 'verbose_name': '2. หน่วยงาน', 'verbose_name_plural': '2. หน่วยงาน'},
        ),
        migrations.AlterModelOptions(
            name='fiscalobjective',
            options={'ordering': ['fiscal_year'], 'verbose_name': '3. กำหนดการประชุม', 'verbose_name_plural': '3. กำหนดการประชุม'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['number'], 'verbose_name': '1. สำนัก', 'verbose_name_plural': '1. สำนัก'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='province',
        ),
        migrations.AlterField(
            model_name='department',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ติดต่อ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทร'),
        ),
        migrations.AlterField(
            model_name='department',
            name='province',
            field=models.CharField(max_length=100, verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='department',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้รับผิดชอบ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.section', verbose_name='สำนัก'),
        ),
        migrations.AlterField(
            model_name='fiscalobjective',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_objectives', to='core.department', verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='fiscalobjective',
            name='fiscal_year',
            field=models.IntegerField(default=2568, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AlterField(
            model_name='fiscalobjective',
            name='meeting_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='สำนัก'),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.IntegerField(verbose_name='ลำดับที่'),
        ),
    ]
