# Generated by Django 4.2.19 on 2025-02-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_file_meeting_form2_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='form_2',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='report_sended',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='result',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='fiscal_year',
            field=models.IntegerField(default=2568, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='form2_file',
            field=models.FileField(blank=True, null=True, upload_to='meeting_files/', verbose_name='ไฟล์ กม.2'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='number',
            field=models.IntegerField(default=1, verbose_name='ครั้งที่'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='meeting_pictures/', verbose_name='รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='meeting_files/', verbose_name='ไฟล์รายงานการประชุม'),
        ),
    ]
