# Generated by Django 4.2.19 on 2025-02-26 02:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fiscalobjective_options_alter_meeting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='ชื่อคำสั่ง')),
                ('number', models.IntegerField(verbose_name='เลขที่คำสั่ง')),
                ('year', models.IntegerField(default=2568, validators=[django.core.validators.MinValueValidator(2500), django.core.validators.MaxValueValidator(2580)], verbose_name='ปี')),
                ('assignment_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่มอบหมาย')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่หมดอายุ')),
                ('file', models.FileField(blank=True, null=True, upload_to='command_files/', verbose_name='ไฟล์')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.department', verbose_name='จังหวัด')),
            ],
            options={
                'verbose_name': '5. คำสั่ง',
                'verbose_name_plural': '5. คำสั่ง',
                'ordering': ['year', 'number'],
            },
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['fiscal_year', 'meeting_date'], 'verbose_name': '4. รายละเอียดการประชุม', 'verbose_name_plural': '4. รายละเอียดการประชุม'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['type', 'number'], 'verbose_name': '1. สำนัก', 'verbose_name_plural': '1. สำนัก'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('P', 'ยังไม่ดำเนินการ'), ('A', 'ดำเนินการแล้ว')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='ชื่อ-สกุล')),
                ('position', models.CharField(max_length=150, verbose_name='ตำแหน่ง')),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Expired')], default='active', max_length=10, verbose_name='สถานะ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='core.command', verbose_name='คำสั่ง')),
            ],
            options={
                'verbose_name': '6. กรรมการ',
                'verbose_name_plural': '6. กรรมการ',
                'ordering': ['command__year', 'command__number', 'full_name'],
            },
        ),
    ]
