# Generated by Django 4.2.19 on 2025-02-26 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_command_alter_meeting_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='assignment_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่มอบหมาย'),
        ),
        migrations.AlterField(
            model_name='command',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่หมดอายุ'),
        ),
        migrations.AlterField(
            model_name='command',
            name='year',
            field=models.IntegerField(default=2568, validators=[django.core.validators.MinValueValidator(2550, message='ปีต้องไม่ต่ำกว่า 2550'), django.core.validators.MaxValueValidator(2580, message='ปีต้องไม่เกิน 2580')], verbose_name='ปี'),
        ),
    ]
